# This is a basic workflow to help you get started with Actions

name: Releases

env:
  PLUGIN_NAME: logseq-drawio-plugin

# Controls when the action will run.
on:
  push:
    branches:
      - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: update
        run: git submodule update --init --recursive
        
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm build
      - run: ls
      - name: upload
        uses: actions/upload-artifact@main
        with:
          name: logseq-drawio-plugin
          path: .

      # - name: Install zip
      #   uses: montudor/action-zip@v1

      # - name: Release
      #   run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
