# This is a basic workflow to help you get started with Actions

name: Sync Releases

env:
  PLUGIN_NAME: logseq-drawio-plugin

# Controls when the action will run.
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  actions: write #  to cancel/stop running workflows (styfle/cancel-workflow-action)
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          submodules: "true"

      - name: Update submodules
        run: git submodule update --remote
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - run: ls

      - name: upload
        uses: actions/upload-artifact@main
        with:
          name: logseq-drawio-plugin
          path: |
            dist
            logo.png
            package.json
            
      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5

      # - name: Install zip
      #   uses: montudor/action-zip@v1

      # - name: Release
      #   run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
